// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkscouhmtgblxdosfpoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrc2NvdWhtdGdibHhkb3NmcG96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODA4MDcsImV4cCI6MjA2Mzg1NjgwN30.X4JpPCb1JPMA0u4l5mKMZVIorE3TEqYJkQIsaXe8Xx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);